### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by avshalomman** [zhuang-li/FACTUAL#1]
Hi @zhuang-li, we are a group of researchers interested in running your code. 
Is there an ETA for its release?

Thanks!

**Comment by zhuang-li** [comment]
Thanks. I was distracted by the EMNLP deadline last week. Will upload the data and pre-trained T5 parsing model this week.

**Comment by avshalomman** [comment]
Great! Thanks a lot

**Comment by zhuang-li** [comment]
Hi, I uploaded the scene graph parsing dataset. The FACTUAL-MR has not been uploaded as I am fixing the format issues. But directly training on scene graph basically performs no differently to training on FACTUAL-MR. I am re-training the parser using flan-T5 instead of T5 and will upload the parsing model to hugging face. But I guess you could train your own models easily with the current dataset.

**Comment by avshalomman** [comment]
Thanks @zhuang-li ! I'd be happy to use the HF model once you upload it

**Comment by zhuang-li** [comment]
@avshalomman Hi. Now, all the data, models and evaluation tools have been uploaded. We also re-implemented the SPICE score. Our SPICE implementation is even more aligned with human judgement in terms of evaluating the performance of image caption generation than the original implementation but offers greater ease of use. Welcome to check it out.
